site_name: team collaboration
nav:
    - Home: index.md
    - About: about.md
    - Team Formation: formation.md
    - Production Mode: production.md
    - Synthesis and Wrap-Up: synthesis.md
theme: readthedocs
