site_name: team collaboration
nav:
    - Home: index.md
    - About: about.md
    - Team Formation: formation.md
    - Workplans: workplan.md
    - Collaboration Tools: tools.md
    - In Person Meetings: InPersonMeetings.md
    - Remote Meetings: RemoteMeetings.md
    - Code of Conduct: conduct.md
    - Data Sharing: data.md
    - Attribution of Effort: authorship.md
    - Formation of Sub-Groups: subgroups.md
    - Synthesis and Wrap-Up: synthesis.md
theme: 
    name: readthedocs
    highlightjs: true
extra_css:
    - css/extra.css
markdown_extensions:
  - admonition
repo_url: https://github.com/NASA-HiMAT/team-collaboration